apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: scribby182/tensorflow-distributed-gpu:latest
              args:
                - --batch-size=64
                - --epochs=10
              resources:
                limits:
                  nvidia.com/gpu: 1
